# Generated by Django 3.2.1 on 2022-09-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
