# Generated by Django 4.0.5 on 2022-07-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_listingid_remove_bid_title_bid_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='listingid',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingid',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
